#!/usr/bin/env bash
#This is a script that displays:
#	the content of the current directory
#	in a list format
#	where only the part of the name after dash is displayed


for entry in 'ls *'
do
	echo $entry
done
