#!/usr/bin/env bash
#This is a script that displays:
#	the content of the current directory
#	in a list format
#	where only the part of the name after dash is displayed


for entry in *;
do
	echo $entry | cut -d '-' -f2
done
